name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test_phaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cd codice_fiscale_rs
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cd codice_fiscale_rs
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cd codice_fiscale_rs
          cargo build --release 